import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from '$lib/server/config';

/**
 * Applies pending Drizzle migrations. Idempotent — safe to run on every boot.
 * Migration SQL lives in ./drizzle (generated by `pnpm db:generate`).
 */
export function runMigrations() {
	const migrationsFolder = resolveMigrationsFolder();
	if (!migrationsFolder) {
		console.warn('[db] no migrations folder found; skipping migrate');
		return;
	}
	fs.mkdirSync(path.dirname(config.databasePath), { recursive: true });
	const sqlite = new Database(config.databasePath);
	sqlite.pragma('journal_mode = WAL');
	const migrationDb = drizzle(sqlite);
	migrate(migrationDb, { migrationsFolder });
	sqlite.close();
	console.log('[db] migrations applied');
}

function resolveMigrationsFolder(): string | null {
	const candidates = [
		path.resolve('drizzle'),
		path.resolve(process.cwd(), 'drizzle'),
		// When bundled in build/, drizzle sits next to the server files.
		path.resolve(fileURLToPath(new URL('.', import.meta.url)), '../../../../drizzle')
	];
	return candidates.find((c) => fs.existsSync(c)) ?? null;
}

// Allow `node src/lib/server/db/migrate.ts` as a standalone CLI.
if (import.meta.url === `file://${process.argv[1]}`) {
	runMigrations();
}
